import pytest
from fdm_sculpt.prusa import TOOL_FIELDS
from fdm_sculpt.regiment_validation import parse_gcode
from fdm_sculpt.slicer_overhang import PROFILE_KEYS, check_diagnostic_profile


def profile():
    config = {key: 'test' for key in PROFILE_KEYS}
    config.update(nozzle_diameter='0.4,0.25,0.4,0.4,0.4', printer_model='XL5IS',
                  printer_technology='FFF', layer_height='0.05', first_layer_height='0.14',
                  support_material='0', support_material_auto='0', wipe_tower='0',
                  complete_objects='0', binary_gcode='0', arc_fitting='disabled', filament_type='PLA')
    config.update({key: '2' for key in TOOL_FIELDS})
    return config


def code(config, second_z=.19):
    return '\n'.join(['; generated by PrusaSlicer 2.9.6', 'T1', 'M83', 'G90',
        'G1 X180 Y180', ';LAYER_CHANGE', ';Z:0.14', ';TYPE:External perimeter',
        'G1 X181 E.1', ';LAYER_CHANGE', f';Z:{second_z}', 'G1 X180 E.1',
        *(f'; {key} = {value}' for key, value in config.items())])


def test_diagnostic_binds_profile_and_keeps_historical_validator():
    expected = profile()
    layers, record = parse_gcode(code(expected),
        profile_validator=lambda actual: check_diagnostic_profile(actual, expected))
    assert len(layers) == 2 and record['continuous_layers']
    with pytest.raises(ValueError):
        parse_gcode(code(expected))  # Historical proof profile remains strict.
    changed = dict(expected, external_perimeter_extrusion_width='0.9')
    with pytest.raises(ValueError, match='external_perimeter_extrusion_width'):
        check_diagnostic_profile(changed, expected)


def test_missing_layers_are_retained_as_failures_for_diagnosis():
    expected = profile()
    validator = lambda actual: check_diagnostic_profile(actual, expected)
    with pytest.raises(ValueError, match='layer heights'):
        parse_gcode(code(expected, .24), profile_validator=validator)
    _, record = parse_gcode(code(expected, .24), profile_validator=validator, record_layer_gaps=True)
    assert not record['continuous_layers']
    assert record['layer_gaps'] == [dict(previous_z_mm=.14, next_z_mm=.24, missing_layers=1)]
    with pytest.raises(ValueError, match='layer heights'):
        parse_gcode(code(expected, .22), profile_validator=validator, record_layer_gaps=True)


def test_diagnostic_rejects_wrong_tool_and_supports():
    expected = profile()
    for key, value in [('perimeter_extruder', '5'), ('support_material', '1')]:
        changed = dict(expected, **{key: value})
        with pytest.raises(ValueError, match=key):
            check_diagnostic_profile(changed, changed)
