"""Artifact, toolpath and layer checks for the 0.25 mm elf trial print."""
from __future__ import annotations

from dataclasses import asdict
import json
import math
from pathlib import Path
import re

from PIL import Image, ImageChops, ImageDraw, ImageFilter

from . import formats, validation, lib3mf_io
from .components.core import component_digest
from .components.elves import ELF_LIBRARY, resolve_elf
from .prusa import VERSION, check_profile, inspect_project, read_settings, sha256
from .regiment_spec import RegimentSpec
from .printability import assess_toolpaths,assess_face_detail


def parse_gcode(text):
    if not re.match(r"; generated by PrusaSlicer " + re.escape(VERSION) + r"(?:\s|$)", text):
        raise ValueError(f"plain-text PrusaSlicer {VERSION} G-code required")
    config = read_settings(text)
    check_profile(config)
    x = y = e = 0.0
    active = None
    relative_e = False
    relative_xyz = False
    layers = []
    current = None
    role = ""
    width = 0.25
    tools = set()
    roles = set()
    selected = set()
    for raw in text.splitlines():
        if raw == ";LAYER_CHANGE":
            current = dict(z=None, paths=[])
            layers.append(current)
        elif raw.startswith(";Z:") and current is not None:
            current["z"] = float(raw[3:])
        elif raw.startswith(";TYPE:"):
            role = raw[6:]
        elif raw.startswith(";WIDTH:"):
            width = float(raw[7:])
        code = raw.split(";", 1)[0].strip()
        if not code:
            continue
        parts = code.split()
        cmd = parts[0]
        values = {m[0]:float(m[1:]) for m in parts[1:] if re.fullmatch(r"[XYZE][-+]?\d*\.?\d+",m)}
        if re.fullmatch(r"T\d+", cmd):
            active = int(cmd[1:])
            selected.add(active)
        elif cmd == "M83":
            relative_e = True
        elif cmd == "M82":
            relative_e = False
        elif cmd == "G90":
            relative_xyz = False
        elif cmd == "G91":
            relative_xyz = True
        elif cmd == "G92":
            e = values.get("E", e)
            x, y = values.get("X", x), values.get("Y", y)
        elif cmd in {"G2", "G3"}:
            raise ValueError("proof inspection requires linear toolpaths")
        elif cmd in {"G0", "G1"}:
            nx = (x+values.get("X",0)) if relative_xyz else values.get("X",x)
            ny = (y+values.get("Y",0)) if relative_xyz else values.get("Y",y)
            delta = values.get("E",0) if relative_e else values.get("E",e)-e
            if current is not None and delta > 0 and math.hypot(nx-x,ny-y)>0.0001:
                tools.add(active)
                roles.add(role)
                current["paths"].append((x-180,y-180,nx-180,ny-180,width,role))
            e = e+values.get("E",0) if relative_e else values.get("E",e)
            x,y = nx,ny
    if tools != {1} or selected != {1}:
        raise ValueError(f"all model/adhesion extrusion must be T1: extrusion={tools}, selections={selected}")
    if any("support" in role.lower() or "wipe tower" in role.lower() for role in roles):
        raise ValueError("unexpected support or wipe tower toolpaths")
    if not layers or any(l["z"] is None or not l["paths"] for l in layers):
        raise ValueError("missing or empty layers")
    z_values = [l["z"] for l in layers]
    if abs(z_values[0]-0.14)>1e-5 or any(abs(b-a-0.05)>1e-5 for a,b in zip(z_values,z_values[1:])):
        raise ValueError("G-code layer heights disagree with 0.14/0.05 mm profile")
    return layers, dict(extrusion_tools=sorted(tools), selected_tools=sorted(selected),
                        roles=sorted(roles), layer_count=len(layers), first_layer_mm=z_values[0],
                        final_z_mm=z_values[-1], model_extrusion_segments=sum(len(l["paths"]) for l in layers),
                        estimated_print_time=config.get("estimated printing time (normal mode)"),
                        filament_used_g_by_tool=config.get("filament used [g]"))


def section_loops(mesh, z):
    """Intersect triangles read-only; sew line ends without repairing geometry."""
    adjacency = {}
    coordinates = {}
    for triangle in mesh.triangles:
        vertices = [mesh.vertices[i] for i in triangle]
        if z <= min(v[2] for v in vertices) or z >= max(v[2] for v in vertices):
            continue
        hits = []
        keys = []
        for a,b in zip(vertices, vertices[1:]+vertices[:1]):
            if (a[2] < z) != (b[2] < z):
                # Identify shared triangle edges by exact endpoint coordinates.
                # Rounding intersection positions can split a valid contour at
                # tiny Boolean edges; topological edge identity does not.
                a,b = sorted((tuple(a),tuple(b)))
                t = (z-a[2])/(b[2]-a[2])
                hits.append((a[0]+(b[0]-a[0])*t, a[1]+(b[1]-a[1])*t))
                keys.append((a,b))
        if len(hits) != 2:
            continue
        if keys[0] == keys[1]:
            continue
        for key,pt in zip(keys,hits):
            coordinates[key] = pt
        adjacency.setdefault(keys[0],set()).add(keys[1])
        adjacency.setdefault(keys[1],set()).add(keys[0])
    loops = []
    while adjacency:
        start = min(adjacency)
        current = start
        loop = []
        while True:
            if current not in adjacency:
                raise ValueError("open contour in evaluated mesh layer")
            loop.append(coordinates[current])
            following = min(adjacency[current])
            adjacency[current].remove(following)
            adjacency[following].remove(current)
            if not adjacency[current]:
                del adjacency[current]
            if following in adjacency and not adjacency[following]:
                del adjacency[following]
            current = following
            if current == start:
                break
        if len(loop) >= 3:
            loops.append(loop)
    return loops


RESOLUTION = 0.025
SIZE = (880, 280)


def pixel(point):
    return (round((point[0]+11)/RESOLUTION), round((3.5-point[1])/RESOLUTION))


def polygon_mask(loop):
    mask = Image.new("1", SIZE)
    ImageDraw.Draw(mask).polygon([pixel(p) for p in loop], fill=1)
    return mask


def solid_loop_indices(loops):
    """Exclude enclosed void boundaries from deposited-island requirements."""
    def area(loop):
        return abs(sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(loop,loop[1:]+loop[:1])))

    def inside(point, polygon):
        x,y = point
        result = False
        for a,b in zip(polygon,polygon[1:]+polygon[:1]):
            if (a[1]>y)!=(b[1]>y) and x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]:
                result = not result
        return result

    areas = [area(loop) for loop in loops]
    return [i for i,loop in enumerate(loops) if sum(
        inside(loop[0],other) for j,other in enumerate(loops) if areas[j]>areas[i])%2==0]


def inspect_layers(mesh, layers, output):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    previous = None
    records = []
    sheets = []
    selected_indices = {0,17,25,50,90,120,155,180,205,235,len(layers)-1}
    for index,layer in enumerate(layers):
        # Mid-plane matches the volume represented by each deposited layer.
        height = 0.14 if index == 0 else 0.05
        z = layer["z"]-height/2+0.000003
        loops = section_loops(mesh,z)
        expected = Image.new("1",SIZE)
        masks = []
        for loop in loops:
            mask = polygon_mask(loop)
            masks.append(mask)
            expected = ImageChops.logical_xor(expected,mask)
        solid_indices = solid_loop_indices(loops)
        masks = [masks[i] for i in solid_indices]
        paths = Image.new("1",SIZE)
        draw = ImageDraw.Draw(paths)
        for x,y,nx,ny,width,role in layer["paths"]:
            if role in {"Skirt/Brim", "Skirt", "Brim"}:
                continue
            draw.line([pixel((x,y)),pixel((nx,ny))],fill=1,width=max(1,round(width/RESOLUTION)))
        disappearing = sum(ImageChops.logical_and(mask,paths).getbbox() is None for mask in masks)
        floating = 0
        growth_mm = 0.0
        if previous is not None:
            # One extrusion width maximum lateral reach is a fixed prototype
            # gate for tiny local ledges; unsupported islands are never allowed.
            supported = previous.convert("L").filter(ImageFilter.MaxFilter(7)).convert("1")
            floating = sum(ImageChops.logical_and(mask,supported).getbbox() is None for mask in masks)
            dilation = previous.convert("L")
            for radius in range(1,42):
                if ImageChops.subtract(expected.convert("L"),dilation).getbbox() is None:
                    break
                dilation = dilation.filter(ImageFilter.MaxFilter(3))
                growth_mm = radius*RESOLUTION
        # Spear columns and the helmet crowns must contain deposited toolpaths.
        surviving_spears = 0
        if 7.8 <= z <= 12.85:
            for x in (-8,-4,0,4,8):
                center = pixel((x+1.2,-0.76))
                if paths.crop((center[0]-22,center[1]-18,center[0]+22,center[1]+18)).getbbox():
                    surviving_spears += 1
        record = dict(index=index,z_mm=round(z,5),contours=len(loops),solid_contours=len(masks),
                      disappearing_contours=disappearing,
                      floating_contours=floating, maximum_lateral_growth_mm=round(growth_mm,3),
                      spear_paths=surviving_spears if 7.8 <= z <= 12.85 else None)
        record["passes"] = (bool(loops) and not disappearing and not floating and growth_mm<=0.25+1e-6
                            and (record["spear_paths"] is None or surviving_spears==5))
        records.append(record)
        if index in selected_indices:
            preview = Image.new("RGB", SIZE, "#171E25")
            preview.paste("#526375",mask=expected)
            preview.paste("#E7C581",mask=paths)
            tile = Image.new("RGB",(SIZE[0],SIZE[1]+30),"#171E25")
            tile.paste(preview,(0,30))
            ImageDraw.Draw(tile).text((12,8),f"Layer {index+1} | Z {layer['z']:.2f} mm | gold: deposited paths, blue: mesh section",fill="white")
            sheets.append(tile)
        previous = expected
    sheet = Image.new("RGB",(SIZE[0],(SIZE[1]+30)*len(sheets)),"#171E25")
    for i,tile in enumerate(sheets):
        sheet.paste(tile,(0,i*(SIZE[1]+30)))
    sheet.save(output/"sliced-layer-proof.png")
    evidence = dict(method="all-layer triangle sections and deposited linear G-code, 0.025 mm raster",
                    lateral_growth_limit_mm=0.25, raster_resolution_mm=RESOLUTION,
                    layers=records, passes=all(r["passes"] for r in records))
    (output/"layer-evidence.json").write_text(json.dumps(evidence,sort_keys=True,indent=2)+"\n")
    return evidence


def analysis_source_hashes():
    package=Path(__file__).resolve().parent
    return {name:sha256(package/name) for name in ('regiment_validation.py','printability.py','prusa.py')}


def assess_build(output, *, automatic_supports=False):
    """Repeatable design feedback without claiming completed validation."""
    output=Path(output).resolve()
    if (output/'modular-print.json').exists():
        from .modular_print import assess
        return assess(output, automatic_supports=automatic_supports)
    if (output/'visual-review.json').exists():
        raise ValueError("visual previews have no print mesh or slice; run regiment build for print checks")
    mesh=formats.read_stl(output/'elf-spearman-proof.stl')
    layers,gcode=parse_gcode((output/'elf-spearman-proof.gcode').read_text())
    layer_evidence=inspect_layers(mesh,layers,output/'previews')
    support=assess_toolpaths(layers,output/'previews')
    details=assess_face_detail(layers,RegimentSpec.load(output/'internal/regiment-spec.json'),output/'previews')
    result=dict(label='printability design review; physical trial pending',
                passes=layer_evidence['passes'] and support['passes'] and details['passes'],
                mesh_layer_checks=layer_evidence['passes'],deposited_layer_support=support['passes'],
                face_details_survive=details['passes'],
                gcode=gcode,support_summary=support['summary'],criteria=support['criteria'],
                analysis_source_sha256=analysis_source_hashes(),
                stl_sha256=sha256(output/'elf-spearman-proof.stl'),
                gcode_sha256=sha256(output/'elf-spearman-proof.gcode'))
    if automatic_supports:
        from .prusa import support_audit
        audit=support_audit(output)
        result['automatic_support_audit']={k:v for k,v in audit.items() if k!='execution'}
    path=output/'printability-review.json'
    path.write_text(json.dumps(result,sort_keys=True,indent=2)+'\n')
    return dict(passes=result['passes'],label=result['label'],
                support_summary=result['support_summary'],report=str(path))


def validate_build(output, compare):
    output,compare = Path(output).resolve(),Path(compare).resolve()
    if any((path/'visual-review.json').exists() for path in (output, compare)):
        raise ValueError("visual previews cannot be digitally validated; run regiment build first")
    if output == compare:
        raise ValueError("determinism requires an independent build directory")
    (output/"manifest.json").write_text(json.dumps(dict(passes=False,label="internal proof - validation pending"))+"\n")
    checks = {}
    metrics = json.loads((output/"internal/mesh-metrics.json").read_text())
    other = json.loads((compare/"internal/mesh-metrics.json").read_text())
    spec = RegimentSpec.load(output/"internal/regiment-spec.json")
    checks["same_seed_geometry"] = (metrics["seed"] == other["seed"] == spec.seed and
                                     metrics["mesh_hash"] == other["mesh_hash"] and
                                     abs(metrics["volume_mm3"]-other["volume_mm3"])<=0.0001 and
                                     all(abs(a-b)<0.0001 for key in ("bounds_min_mm","bounds_max_mm")
                                         for a,b in zip(metrics[key],other[key])) and
                                     sha256(output/"internal/resolved-plans.json")==sha256(compare/"internal/resolved-plans.json") and
                                     sha256(output/"internal/regiment-spec.json") == sha256(compare/"internal/regiment-spec.json"))
    mesh = formats.read_stl(output/"elf-spearman-proof.stl")
    checks["metrics_bound_to_stl"] = metrics["stl_sha256"] == sha256(output/"elf-spearman-proof.stl")
    # STL stores independent triangle corners. Reconstruct exact shared vertex
    # identity for topology analysis; require that no triangles are removed.
    indexed = formats.sanitize_stl_mesh(mesh)
    checks["stl_requires_no_face_removal"] = indexed.removed_triangle_count==0
    analysis = validation.analyze_mesh(indexed.mesh)
    checks["topology"] = (analysis.watertight and analysis.manifold and analysis.outward_facing
                          and analysis.positive_volume and analysis.connected_components==1)
    checks["self_intersections"] = metrics["self_intersection_count"] == 0
    checks["triangle_budget"] = analysis.triangle_count <= 250000
    checks["structural_probes"] = metrics["features"]["passes"]
    bounds = [[min(v[i] for v in mesh.vertices),max(v[i] for v in mesh.vertices)] for i in range(3)]
    checks["scale"] = all(abs(a-b)<0.02 for a,b in zip([v for pair in bounds for v in pair],[-10,10,-2.5,2.5,0,13]))
    plans = json.loads((output/"internal/resolved-plans.json").read_text())
    expected = [resolve_elf(ELF_LIBRARY.resolve(i.component_id,i.version),i) for i in spec.instances]
    checks["component_recipe_hashes"] = [component_digest(p) for p in plans] == [component_digest(p) for p in expected]
    checks["source_scene"] = (output/"internal/elf-spearman-proof.blend").stat().st_size>1000
    checks["saved_provenance"] = json.loads((output/"internal/saved-provenance.json").read_text())["passes"]
    checks["technical_views"] = all((output/"previews"/(name+".png")).read_bytes().startswith(b"\x89PNG")
                                      for name in ("front","side","three-quarter","face-grip-detail","grip-detail","pose-detail"))
    generic = formats.read_3mf(output/"elf-spearman-proof.3mf")
    checks["generic_3mf"] = len(generic.volumes)==1 and formats.mesh_hash(generic.volumes[0].mesh)==formats.mesh_hash(mesh)
    generic_inspection = lib3mf_io.inspect_3mf(output/"elf-spearman-proof.3mf", expected_object_count=1,expected_material_count=1)
    checks["lib3mf"] = generic_inspection.passed
    project = inspect_project(output/"elf-spearman-proof-prusa.3mf")
    checks["project"] = project["readable"]
    slicer = json.loads((output/"prusa/slicer-evidence.json").read_text())
    checks["installed_presets_unchanged"] = slicer["installed_inputs_unchanged"]
    checks["slicer_artifacts"] = (slicer["export"]["artifact_sha256"]==sha256(output/"elf-spearman-proof-prusa.3mf") and
                                  slicer["reopen_slice"]["artifact_sha256"]==sha256(output/"elf-spearman-proof.gcode"))
    profile = output/"prusa/profile"
    profile_record = json.loads((profile/"profile-manifest.json").read_text())
    checks["profile_snapshots"] = (sha256(profile/"prusa-xl-0.25-0.05.ini")==profile_record["settings_sha256"] and
                                   all(sha256(profile/p["snapshot"])==p["sha256"] for p in profile_record["inputs"]))
    layers,gcode = parse_gcode((output/"elf-spearman-proof.gcode").read_text())
    layer_evidence = inspect_layers(mesh,layers,output/"previews")
    checks["sliced_layers"] = layer_evidence["passes"]
    printability = assess_toolpaths(layers,output/"previews")
    checks["deposited_layer_support"] = printability["passes"]
    checks['face_details_survive'] = assess_face_detail(layers,spec,output/'previews')['passes']
    checks["tip_survival"] = gcode["final_z_mm"]>=12.9
    label = "digitally validated" if all(checks.values()) else "internal proof - validation failed"
    instructions = (
        f"# Aurelian leafguard trial strip\n\n{label}. Internal prototype; user visual review and physical trial pending.\n\n"
        "Five figures, approximately 8 mm sole-to-eye, fused to a 20 x 5 x 1 mm strip.\n\n"
        "Open `internal/elf-spearman-proof.blend` in Blender to orbit the fused scene. "
        "The source collection is hidden and retains the parametric geometry. Technical views and the sliced-layer sheet are in `previews/`.\n\n"
        "For the trial print, open `elf-spearman-proof-prusa.3mf` as a PrusaSlicer project. "
        "It targets the five-tool Prusa XL with PLA in tool 2's 0.25 mm nozzle. "
        "The supplied plain-text G-code uses T1 exclusively, 0.05 mm layers, a 0.14 mm first layer, "
        "three perimeters and a removable 6 mm brim. Print upright with the strip flat on the bed. "
        "No removable supports or wipe tower are generated. Cloaks and shield clasps remain part of the miniature.\n\n"
        f"Slicer estimate: {gcode.get('estimated_print_time')}. Filament grams by tools 1-5: {gcode.get('filament_used_g_by_tool')}.\n\n"
        "The mono STL and generic 3MF contain the same fused geometry without printer settings. "
        "`manifest.json` records validation, geometry comparison and artifact hashes; `prusa/` holds the resolved profile and slicer logs. "
        "Installed presets were left unchanged. These components remain review candidates; archers and command units are outside this delivery.\n")
    (output/"PRINT-README.md").write_text(instructions,encoding="utf-8")
    result = dict(schema_version=1, passes=all(checks.values()), checks=checks,
                  label=label,
                  review_status="user visual review and trial print pending",
                  geometry_hash=metrics["mesh_hash"], compare_directory=str(compare),
                  geometry_hash_method="repository solid occupancy lattice, corroborated by same recipe plans, bounds and volume",
                  mesh_analysis=asdict(analysis), gcode=gcode,
                  validation_source_sha256=analysis_source_hashes(),
                  printability=printability['summary'],printability_criteria=printability['criteria'],
                  generic_3mf_inspection=generic_inspection.to_dict(),
                  prototype_limits=dict(structural_wall_mm=0.75,shaft_mm=1.0,relief_mm=0.25,gap_mm=0.5,
                                        note="terminal tapered tips and attached decorative edges are not structural walls"),
                  artifacts={str(p.relative_to(output)).replace('\\','/'):sha256(p) for p in sorted(output.rglob("*"))
                             if p.is_file() and p.name != "manifest.json" and "isolated-settings" not in p.parts})
    (output/"manifest.json").write_text(json.dumps(result,sort_keys=True,indent=2)+"\n")
    return dict(passes=result["passes"],label=result["label"],checks=checks,manifest=str(output/"manifest.json"))
