"""Background Blender Boolean Union export; geometry validation is opt-out by request."""
import hashlib
import json
from pathlib import Path
import sys
import traceback
import os
import subprocess
import time

from . import atelier
from .review import find_blender
from .workshop import DATA, JOBS, job_status, write


def blender_union(pinned,directory):
    output=directory/'blender-union'
    output.mkdir()
    job=atelier.prepare(pinned['assembly'],seed=pinned['seed'])
    job['output']=str(output.resolve())
    write(output/'union-job.json',job)
    blender=find_blender()
    if blender is None:
        raise RuntimeError('Blender 5.1.2 is required')
    with (output/'blender.log').open('w') as log:
        subprocess.run([str(blender),'--background','--factory-startup','--python-exit-code','1',
                        '--python',str(Path(__file__).with_name('workshop_union_blender.py')),
                        '--',str((output/'union-job.json').resolve())],
                       stdout=log,stderr=subprocess.STDOUT,check=True,timeout=3600)
    return output,json.loads((output/'union-result.json').read_text())


def export(job_id):
    directory = JOBS/job_id
    pinned = json.loads((directory/'plan.json').read_text())
    status = job_status(job_id)
    status['pid'] = os.getpid()
    write(directory/'process.json',dict(pid=os.getpid()))
    def update(state, message, **extra):
        status.update(state=state,message=message,**extra)
        write(directory/'status.json',status)
    try:
        started=time.perf_counter()
        update('running','Blender is combining the row and exporting the STL',stage='boolean-union',
               validation_performed=False,export_mode='unchecked-blender-manifold-union')
        output,result=blender_union(pinned,directory)
        report=dict(plan=pinned,blender=result,validation_performed=False,digitally_validated=False)
        stl = (output/'row.stl').read_bytes()
        sha = hashlib.sha256(stl).hexdigest()
        (DATA/'downloads').mkdir(parents=True,exist_ok=True)
        (DATA/'downloads'/f'{sha}.stl').write_bytes(stl)
        write(DATA/'downloads'/f'{job_id}-report.json',report)
        update('complete','STL generated by Blender. Unchecked output.',
               stage='complete',download=dict(url=f'/data/downloads/{sha}.stl',filename=f'infantry-row-{job_id[:8]}.stl',
                                             sha256=sha,bytes=len(stl)),
               report_url=f'/data/downloads/{job_id}-report.json',slots=pinned['slots'],
               elapsed_seconds=round(time.perf_counter()-started,3),union_seconds=result.get('union_seconds'))
    except Exception as exc:
        traceback.print_exc()
        log=directory/'blender-union/blender.log'
        write(DATA/'downloads'/f'{job_id}-report.json',dict(plan=pinned,error=str(exc),stage=status.get('stage'),
              blender_log=log.read_text(errors='replace')[-12000:] if log.exists() else '',validation_performed=False))
        update('failed','Blender could not finish the export. See the export report for details.',
               report_url=f'/data/downloads/{job_id}-report.json')


if __name__ == '__main__':
    export(sys.argv[1])
